NetFlex.WEB/Controllers/AdminController.cs
using AutoMapper;
using NetFlex.DAL.Constants;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NetFlex.BLL.Infrastructure;
using NetFlex.BLL.Interfaces;
using NetFlex.BLL.ModelsDTO;
using NetFlex.DAL.Enums;
using NetFlex.WEB.ViewModels;
using Microsoft.AspNetCore.Identity;
using PagedList;

namespace NetFlex.WEB.Controllers
{
    //[Authorize(Policy = Constants.Policies.RequireAdmin)]
    public class AdminController : Controller
	{
        RoleManager<IdentityRole> _roleManager;

        private readonly IVideoService _videoService;
		public readonly IRatingService _ratingService;
		public readonly IUserService _userService;
        public readonly IRoleService _roleService;
        public AdminController(RoleManager<IdentityRole> rm,IVideoService videoService, IRatingService ratingService, IUserService userService, IRoleService roleService)
        {
            _videoService = videoService;
            _ratingService = ratingService;
			_userService = userService;
            _roleService = roleService;
            _roleManager = rm;
        }

        public IActionResult Index() => View();

        public IActionResult SubsriptionPlans() => View();

        public IActionResult Episodes() => View();

        public IActionResult CreateRole() => View();

        public async Task<IActionResult> EditUserRole(string userId)
        {
            // ïîëó÷àåì ïîëüçîâàòåëÿ

            var user = await _userService.GetUser(userId);
            if (user != null)
            {
                // ïîëó÷åì ñïèñîê ðîëåé ïîëüçîâàòåëÿ

                var userRoles = await _userService.GetRoles(user.UserName);

                var allRolesDto = await _roleService.GetRoles();

                var config = new MapperConfiguration(cfg => cfg.CreateMap<RoleDTO, RoleViewModel>());
                var mapper = new Mapper(config);
                var allRoles = mapper.Map<IEnumerable<RoleDTO>, List<RoleViewModel>>(allRolesDto);


                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles.ToList(),
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }

        public async Task<IActionResult> Users(int? page, string searchString)
		{
            var getUsers = await _userService.GetUsers();

			for (int i = 0; i < 10; i++)
			{
                getUsers = getUsers.Concat(getUsers);
			}

            var users = getUsers.Select(u => new AdminUserVievModel
            {
                UserId = u.Id,
                UserName = u.UserName,
                Email = u.Email,
                PhoneNumber = u.PhoneNumber,
                LockoutEnabled = u.LockoutEnable,
                Avatar = u.Avatar
            }).AsQueryable();

            int usersCount = getUsers.Count();

            if (searchString != null)
            {
                users = users.Where(v => v.Email.Contains(searchString) || v.UserId.Contains(searchString));
                usersCount = users.ToList().Count();
            }
            ViewBag.searchString = searchString;
            users = users.ToPagedList(page != null ? (int)page : 1, 32).AsQueryable();
            
            UsersPageViewModel model = new UsersPageViewModel()
            {
                UsersCount = usersCount,
                Users = users.AsEnumerable()
            };
            return View(model);
        }

		public async Task<IActionResult> Serials()
		{
            try
            {
                var getSerials = await _videoService.GetSerials();
                var config = new MapperConfiguration(cfg => cfg.CreateMap<SerialDTO, SerialViewModel>());
                var mapper = new Mapper(config);
                var serials = mapper.Map<IEnumerable<SerialDTO>, IEnumerable<SerialViewModel>>(getSerials);

                var getGenres = await _videoService.GetGenres();
                var config2 = new MapperConfiguration(cfg => cfg.CreateMap<GenreDTO, GenreViewModel>());
                var mapper2 = new Mapper(config);
                var genres = mapper.Map<IEnumerable<GenreDTO>, IEnumerable<GenreViewModel>>(getGenres);


                //var serialsView = new FullVideoInfoViewModel
                //{
                //    Serials = serials.ToList(),
                //    Genres = genres.ToList(),
                //};

                return View();
            }
            catch
            {

            }
            return View();
        }

		public async Task<IActionResult> Films()
		{
            try
            {
                var getFilms = await _videoService.GetFilms();
                var config = new MapperConfiguration(cfg => cfg.CreateMap<FilmDTO, FilmViewModel>());
                var mapper = new Mapper(config);
                var films = mapper.Map<IEnumerable<FilmDTO>, IEnumerable<FilmViewModel>>(getFilms);

                films.OrderBy(v => v.Title);

                return View(films);
            }
            catch
            {

            }
            return View();
		}

        public async Task<IActionResult> Genres() 
        {
            var getGenres = await _videoService.GetGenres();
            var config = new MapperConfiguration(cfg => cfg.CreateMap<GenreDTO, GenreViewModel>());
            var mapper = new Mapper(config);
            var genres = mapper.Map<IEnumerable<GenreDTO>, List<GenreViewModel>>(getGenres);

            return View(genres);
        }
        public async Task<List<GenreViewModel>> GetGenres()
        {
            var getGenres = await _videoService.GetGenres();
            var config = new MapperConfiguration(cfg => cfg.CreateMap<GenreDTO, GenreViewModel>());
            var mapper = new Mapper(config);
            var genres = mapper.Map<IEnumerable<GenreDTO>, List<GenreViewModel>>(getGenres);

            return genres;
        }

        public async Task<IActionResult> Roles()
        {
            var getRoles = await _roleService.GetRoles();
            var config = new MapperConfiguration(cfg => cfg.CreateMap<RoleDTO, RoleViewModel>());
            var mapper = new Mapper(config);
            var roles = mapper.Map<IEnumerable<RoleDTO>, List<RoleViewModel>>(getRoles);

            return View(roles);
        }

		#region Lagacy

        [HttpPost]
        public IActionResult UploadSerial(SerialViewModel model)
        {
            try
            {
                var configS = new MapperConfiguration(cfg => cfg.CreateMap<SerialViewModel, SerialDTO>());
                var mapperS = new Mapper(configS);
                var serialDTO = mapperS.Map<SerialViewModel, SerialDTO>(model);

                var configE = new MapperConfiguration(cfg => cfg.CreateMap<EpisodeViewModel, EpisodeDTO>());
                var mapperE = new Mapper(configE);
                var episdoesDTO = mapperE.Map<List<EpisodeViewModel>, List<EpisodeDTO>>(model.Episodes);

                _videoService.UploadSerial(serialDTO);
                

                foreach(var item in episdoesDTO)
                {
                    item.SerialId = model.Id;
                    _videoService.UploadEpisode(item);
                }

                foreach (var item in model.Genres)
                {
                    var genresDto = new GenreVideoDTO
                    {
                        Id = Guid.NewGuid(),
                        ContentId = model.Id,
                        GenreName = item.GenreName,
                    };
                    _videoService.SetGenres(genresDto);
                }
            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError(ex.Property, ex.Message);
            }
            return RedirectToAction("Serials");
        }

        [HttpPost]
        public async Task<IActionResult> ChangeUserRoles(string userId, List<string> roles)
        {
            var user = await _userService.GetUser(userId);

            if (user != null)
            {
                var userRoles = await _userService.GetRoles(user.UserName);
                var addedRoles = roles.Except(userRoles);
                var removedRoles = userRoles.Except(roles);

                await _roleService.GiveRoles(addedRoles.ToList(), user.UserName);

                await _roleService.TakeAwayRoles(removedRoles.ToList(), user.UserName);

                return RedirectToAction("Users");
            }

            return NotFound();
        }

		#endregion

		#region Partials
		#region Add

        public async Task<IActionResult> GetEditUserRolesPartial(string userID)
        {
            var user = await _userService.GetUser(userID);
            if (user != null)
            {
                var userRoles = await _userService.GetRoles(user.UserName);

                var allRolesDto = await _roleService.GetRoles();

                var config = new MapperConfiguration(cfg => cfg.CreateMap<RoleDTO, RoleViewModel>());
                var mapper = new Mapper(config);
                var allRoles = mapper.Map<IEnumerable<RoleDTO>, List<RoleViewModel>>(allRolesDto);


                ChangeRoleViewModel model = new()
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles.ToList(),
                    AllRoles = allRoles
                };
                return PartialView("Partial/_EditUserRoles", model);
            }

            return NotFound();
        }
        
        public IActionResult GetAddRolesPartial()
		{
            return PartialView("Partial/_AddRole");
        }
        public IActionResult GetAddGenrePartial()
        {
            return PartialView("Partial/_AddGenre");
        }
        public IActionResult GetAddMoviePartial()
        {

NetFlex.WEB/Controllers/MainController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using NetFlex.BLL.Interfaces;
using NetFlex.BLL.ModelsDTO;
using NetFlex.WEB.ViewModels;

namespace NetFlex.WEB.Controllers
{
	public class MainController : Controller
	{
		private IVideoService _videoService;

		public MainController(IVideoService videoService)
		{
			_videoService = videoService;
		}

		public async Task<IActionResult> IndexAsync()
		{
			var getFilms = await _videoService.GetFilms();
			var config = new MapperConfiguration(cfg => cfg.CreateMap<FilmDTO, FilmViewModel>());
			var mapper = new Mapper(config);
			var movies = mapper.Map<IEnumerable<FilmDTO>, IEnumerable<FilmViewModel>>(getFilms);

			var getSerials = await _videoService.GetSerials();
			var config1 = new MapperConfiguration(cfg => cfg.CreateMap<SerialDTO, SerialViewModel>());
			var mapper1 = new Mapper(config1);
			var serials = mapper1.Map<IEnumerable<SerialDTO>, IEnumerable<SerialViewModel>>(getSerials);

			var model = new MainPageViewModel()
			{
				Series = serials.ToList(),
				Movies = movies.ToList()
			};

			return User.Identity.IsAuthenticated ? View(model) : RedirectToAction("Index", "Home");
		}
	}
}

NetFlex.WEB/Controllers/PopularController.cs
using Microsoft.AspNetCore.Mvc;

namespace NetFlex.WEB.Controllers
{
	public class PopularController : Controller
	{
		public IActionResult Index()
		{
			return User.Identity.IsAuthenticated ? View() : RedirectToAction("Index", "Home");
		}
	}
}

NetFlex.WEB/Controllers/VideoController.cs
using Microsoft.AspNetCore.Mvc;
using NetFlex.BLL.Infrastructure;
using NetFlex.BLL.Interfaces;
using NetFlex.BLL.ModelsDTO;
using NetFlex.WEB.ViewModels;
using AutoMapper;

namespace NetFlex.WEB.Controllers
{
	public class VideoController : Controller
	{
		private readonly IVideoService _videoService;
        private readonly IUserService _userService;
        public readonly IRatingService _ratingService;
        public readonly IReviewService _reviewService;

        public VideoController(IVideoService videoService, IReviewService reviewService,IRatingService ratingService, IUserService userService)
        {
            _videoService = videoService;
            _reviewService = reviewService;
            _ratingService = ratingService;
            _userService = userService;
        }

        public IActionResult Index(Guid id)
		{
            return User.Identity.IsAuthenticated ? View() : RedirectToAction("Index", "Home");
        }

		public async Task<IActionResult> Movie(Guid id)
        {
            try
            {
                FilmDTO filmDTO = await _videoService.GetFilm(id);

                var getFilm = await _videoService.GetFilm(id);
                var config = new MapperConfiguration(cfg => cfg.CreateMap<FilmDTO, FilmViewModel>());
                var mapper = new Mapper(config);
                var movie = mapper.Map<FilmDTO, FilmViewModel>(getFilm);

                var getGenres = await _videoService.GetGenres(id);
                var config1 = new MapperConfiguration(cfg => cfg.CreateMap<GenreVideoDTO, GenreVideosViewModel>());
                var mapper1 = new Mapper(config1);
                var genres = mapper1.Map<IEnumerable<GenreVideoDTO>, List<GenreVideosViewModel>>(getGenres);

				var getReviews = await _reviewService.GetReviews(id);
				var config2 = new MapperConfiguration(cfg => cfg.CreateMap<ReviewDTO, ReviewViewModel>());
				var mapper2 = new Mapper(config2);
				var reviews = mapper2.Map<IEnumerable<ReviewDTO>, List<ReviewViewModel>>(getReviews);

				var fullVideo = new FullVideoInfoViewModel()
                {
                    Film = movie,
                    Genres = genres,
                    Reviews = reviews
                };

                return View(fullVideo);
            }
            catch (ValidationException ex)
            {
                return Content(ex.Message);
            }
        }
        public async Task<IActionResult> Serial(Guid id)
        {
            try
            {
                var getSerial = await _videoService.GetSerial(id);
                var config = new MapperConfiguration(cfg => cfg.CreateMap<SerialDTO, SerialViewModel>());
                var mapper = new Mapper(config);
                var serial = mapper.Map<SerialDTO, SerialViewModel>(getSerial);

                var getGenres = await _videoService.GetGenres(id);
                var config1 = new MapperConfiguration(cfg => cfg.CreateMap<GenreVideoDTO, GenreVideosViewModel>());
                var mapper1 = new Mapper(config1);
                var genres = mapper1.Map<IEnumerable<GenreVideoDTO>, List<GenreVideosViewModel>>(getGenres);

                var getReviews = await _reviewService.GetReviews(id);
                var config2 = new MapperConfiguration(cfg => cfg.CreateMap<ReviewDTO, ReviewViewModel>());
                var mapper2 = new Mapper(config2);
                var reviews = mapper2.Map<IEnumerable<ReviewDTO>, List<ReviewViewModel>>(getReviews);

                var getEpisodes = await _videoService.GetEpisodes(id);
                var config3 = new MapperConfiguration(cfg => cfg.CreateMap<EpisodeDTO, EpisodeViewModel>());
                var mapper3 = new Mapper(config3);
                var episodes = mapper3.Map<IEnumerable<EpisodeDTO>, List<EpisodeViewModel>> (getEpisodes);

                serial.Episodes = episodes;

                var fullVideo = new FullVideoInfoViewModel()
                {
                    Serial = serial,
                    Genres = genres,
                    Reviews = reviews,
                };

                return View(fullVideo);
            }
            catch (ValidationException ex)
            {
                return Content(ex.Message);
            }
        }

        [HttpGet("Movie")]
        public async Task<IActionResult> GetFilm(Guid movieId)
        {
            var getFilm = await _videoService.GetFilm(movieId);
            var config = new MapperConfiguration(cfg => cfg.CreateMap<FilmDTO, FilmViewModel>());
            var mapper = new Mapper(config);
            var movie = mapper.Map<FilmDTO, FilmViewModel>(getFilm);
            return View(movie);
        }

        [HttpPost("PublicReview")]
        public async Task<IActionResult> PublicReview(ReviewViewModel model)
        {
            try
            {
                var config = new MapperConfiguration(cfg => cfg.CreateMap<ReviewViewModel, ReviewDTO>());
                var mapper = new Mapper(config);
                var reviewDTO = mapper.Map<ReviewViewModel, ReviewDTO>(model);
                await _reviewService.PublishReview(reviewDTO);
                await _ratingService.SetRating(reviewDTO);

            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError(ex.Property, ex.Message);
            }
            return StatusCode(200);
        }

        [HttpPost]
        public async Task<IActionResult> AddToMyList(UserFavoriteViewModel model)
        {
            try
            {
                var myList = await _userService.GetMyList(model.UserId);
                if (myList.Where(x => x.ContentId == model.ContentId) == null)
                {
                    var config = new MapperConfiguration(cfg => cfg.CreateMap<UserFavoriteViewModel, UserFavoriteDTO>());
                    var mapper = new Mapper(config);
                    var favoritesDto = mapper.Map<UserFavoriteViewModel, UserFavoriteDTO>(model);

                    await _userService.AddToMyList(favoritesDto);
                };
            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError(ex.Property, ex.Message);
            }
            return StatusCode(200);
        }

    }
}

NetFlex.WEB/Views/Shared/_AdminLayout.cshtml
@using NetFlex.DAL.Enums

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"]</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/NetFlex.WEB.styles.css" asp-append-version="true" />
	<script src="https://kit.fontawesome.com/3ee70c58bc.js" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="~/css/Admin/Admin.min.css" />
	<link rel="stylesheet" href="~/lib/jquery-confirm/css/jquery-confirm.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/lib/jquery-ui-1.12.1/jquery-ui.css">
	<link rel="stylesheet" href="~/css/PanelsUI.css" />
	@await RenderSectionAsync("Styles", required: false)
</head>
<body>
	
	@Html.AntiForgeryToken()
	<div class="container">
		<main role="main" class="pb-3">
			<div class="wrapper">
				<div class="menu">
					<a class="button" asp-controller="Main" asp-action="Index">
						<i class="fa-solid fa-reply-all"></i>
						<span>Return to main</span>
					</a>
					<hr />
					@{
						//Enum.TryParse(ViewData["CurrentPage"] as string, out AdminPages _page);
						Func<AdminPages, string> CheckSelected = (e) => { return (e == (AdminPages)ViewData["CurrentPage"]).ToString(); };
					}
					<a class="button" asp-controller="Admin" asp-action="Index" selected="@CheckSelected(AdminPages.Statistics)">
						<i class="fa-solid fa-chart-line"></i>
						<span>Statistics</span>
					</a>
					<a class="button" asp-controller="Admin" asp-action="Users" selected="@CheckSelected(AdminPages.Users)">
						<i class="fa-brands fa-accessible-icon"></i>
						<span>Users</span>
					</a>
					<a class="button" asp-controller="Admin" asp-action="Roles" selected="@CheckSelected(AdminPages.Roles)">
						<i class="fa-brands fa-accessible-icon"></i>
						<span>Roles</span>
					</a>
					<hr />
					<a class="button" asp-controller="Admin" asp-action="SubsriptionPlans" selected="@CheckSelected(AdminPages.Plans)">
						<i class="fa-solid fa-circle-dollar-to-slot"></i>
						<span>Subscription plans</span>
					</a>
					<hr />
					<a class="button" asp-controller="Admin" asp-action="Genres" selected="@CheckSelected(AdminPages.Genres)">
						<i class="fa-solid fa-mars-and-venus"></i>
						<span>Genres</span>
					</a>
					<a class="button" asp-controller="Admin" asp-action="Films" selected="@CheckSelected(AdminPages.Movies)">
						<i class="fa-solid fa-clapperboard"></i>
						<span>Movies</span>
					</a>
					<a class="button" asp-controller="Admin" asp-action="Serials" selected="@CheckSelected(AdminPages.Series)">
						<i class="fa-solid fa-film"></i>
						<span>Series</span>
					</a>
					<a class="button" asp-controller="Admin" asp-action="Episodes" selected="@CheckSelected(AdminPages.Episodes)">
						<i class="fa-solid fa-film"></i>
						<span>Episodes</span>
					</a>
				</div>
				<div class="content">
					@RenderBody()
				</div>
			</div>
		</main>
	</div>
	<div id="loader">
		<img src="~/images/mini-logo.svg" />
	</div>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/jquery-ui-1.12.1/jquery-ui.js"></script>
	<script src="~/lib/jquery-confirm/dist/jquery-confirm.min.js" asp-append-version="true"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/AdminPage.js"></script>
	@await RenderSectionAsync("Scripts", required: false)
	<script>
		window.addEventListener('DOMContentLoaded', e => {
			document.querySelector("#loader").setAttribute("loaded", "true");
		});
	</script>
</body>
</html>

NetFlex.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - NetFlex.WEB</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/NetFlex.WEB.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/css/Main/Main.css">
	<script src="https://kit.fontawesome.com/3ee70c58bc.js" crossorigin="anonymous"></script>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600;700;800;900&display=swap" rel="stylesheet">
	@await RenderSectionAsync("Styles", required: false)
</head>
<body>
	<main role="main" class="pb-3">
		@RenderBody()
	</main>

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

NetFlex.WEB/Views/Shared/_MainLayout.cshtml
@using Microsoft.AspNetCore.Identity
@using NetFlex.DAL.EF
@inject SignInManager<ApplicationUser> _sim

@{
	var topicHeight = "";
	if ((bool)ViewData["mainpage"] == false)
	{
		topicHeight = "height: 30vh !important;";
	}
}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<script src="https://kit.fontawesome.com/3ee70c58bc.js" crossorigin="anonymous"></script>
	<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600;700;800;900&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="~/css/MainLayout.css">
	@await RenderSectionAsync("Styles", required: false)

</head>
<body>
	<header>
		<div class="logo"></div>
		<a asp-controller="Main" class="nav_button">Main</a>
		<a asp-controller="Movies" class="nav_button">Movies</a>
		<a asp-controller="Series" class="nav_button">Series</a>
		<a asp-controller="Popular" class="nav_button">Popular</a>
		<a asp-controller="MyList" class="nav_button">My list</a>
		<div class="right">
			<div class="user">
				<span>@User.Identity.Name</span>
				<i class="fa-solid fa-user"></i>
				<div class="account_buttons">
					<a href="~/Identity/Account/Manage" type="submit">Settings</a>
					@if(User.IsInRole("Administrator")){
						<a href="~/admin" type="submit">Admin panel</a>
					}
					<form asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Page("/", new { area = "" })" method="post">
						<button type="submit">Logout</button>
					</form>
				</div>
			</div>
		</div>
	</header>

	<div class="topic" style="@topicHeight">
		<video autoplay muted loop class="preview">
			<source src="https://raw.githubusercontent.com/1dxrpz/video-player-test-js/main/videos/background.mp4" type="video/mp4">
		</video>
		<div class="dot"></div>
		<div class="content">
			<div class="wrapper">
				<div class="logo">
					<img src="~/images/Logo.svg" />
				</div>
				<div class="text">Watch anywhere. Cancel at any time</div>
			</div>
		</div>
	</div>

	@RenderBody()

	<div id="loader" loaded="false">
		<img src="~/images/mini-logo.svg" />
	</div>

	<script type="text/javascript">
		var video = document.querySelector(".preview");
		var logo = document.querySelector(".wrapper>.logo");
		var header = document.querySelector("header");
		var logoY = logo.getBoundingClientRect().top;

		window.onscroll = (e) => {
			var val = window.scrollY >= logoY - header.getBoundingClientRect().height - 10;
			header.setAttribute('scroll', val);
			if (val) {
				header.style.top = (logoY - header.getBoundingClientRect().height - 10) + 'px';
			} else {
				header.style.top = '0px';
			}
			video.style.top = window.scrollY * 0.5 + 'px';
		}
		video.addEventListener('loadeddata', (e) => {
		   if(video.readyState >= 3){
			   document.querySelector("#loader").setAttribute("loaded", "true");
		   }
		});
	</script>
	<script src="https://cdn.jsdelivr.net/npm/@@splidejs/splide@4.0.1/dist/js/splide.min.js"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

NetFlex.WEB/Views/Shared/_VideoLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NetFlex.WEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="https://kit.fontawesome.com/3ee70c58bc.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/VideoPlayer.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Video/Video.min.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/css/MainLayout.css">
	@await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
		<div class="logo"></div>
		<a asp-controller="Main" asp-action="Index" class="nav_button">Main</a>
		<a asp-controller="Movies" asp-action="Index" class="nav_button">Movies</a>
		<a asp-controller="Series" asp-action="Index" class="nav_button">Series</a>
		<a asp-controller="Popular" asp-action="Index" class="nav_button">Popular</a>
		<a asp-controller="MyList" asp-action="Index" class="nav_button">My list</a>
		<div class="right">
			<div class="user">
				<span>@User.Identity.Name</span>
				<i class="fa-solid fa-user"></i>
				<div class="account_buttons">
					<a href="~/Identity/Account/Manage" type="submit">Settings</a>
					@if(User.IsInRole("Administrator")){
						<a href="~/admin" type="submit">Admin panel</a>
					}
					<form asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Page("/", new { area = "" })" method="post">
						<button type="submit">Logout</button>
					</form>
				</div>
			</div>
		</div>
	</header>
	@RenderBody()
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>